tasks:
  - init: |
      docker-compose pull
      npm install
      cp .env.example .env
      npx drizzle-kit migrate
  - command: |
      docker-compose up -d

ports:
  - port: 5432
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
